language: cpp
sudo: required
dist: trusty
matrix:
  include:
    # gcc 5 on linux
    - env: COMPILER=g++-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
          packages:
            - gcc-5
            - g++-5
    # clang on osx
    - os: osx
      compiler: clang
before_install:
before_script:
script:
  - make
  - make test
after_success:
notifications:
  email: false
