skip_tags: true
skip_commits:
  files:
    - .travis.yml
platform:
  - x64
install:
  - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade
  - C:\msys64\usr\bin\pacman --noconfirm --sync mingw-w64-x86_64-toolchain
  - C:\msys64\usr\bin\pacman --noconfirm --sync mingw-w64-x86_64-cmake
build_script:
  - set MSYSTEM=MINGW64
  - set CC=gcc
  - set CXX=g++
  - echo %PATH%
  - C:\msys64\usr\bin\bash -l -c "echo $PATH"
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && mingw32-make"
#  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && mingw32-make test"
  - C:\msys64\usr\bin\bash -l -c "cd /c/projects/xlsxconverter && mingw32-make release OS=windows ARCH=x86_64"
artifacts:
- path: "build¥*.zip"
  name: release
